export const SET_APP_LOADED = 'setAppLoaded'
export const SET_CHARACTERS_LOADED = 'setCharactersLoaded'
export const SET_CHARACTERS = 'setCharacters'
export const SET_CURRENT_CHARACTERS_PAGE = 'setCurrentCharactersPage'
export const UPDATE_SHOW_GLOBAL_LOADER = 'updateShowGlobalLoader'
